apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: prod-
images:
  - name: local/api
    newName: your-registry.example.com/microdemo/api
    newTag: v1.0.0
  - name: local/worker
    newName: your-registry.example.com/microdemo/worker
    newTag: v1.0.0
patches:
  - target:
      version: v1
      kind: Deployment
      name: api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3

  - path: patch-imagepullsecrets.yaml
    target:
      kind: Deployment
