apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: microdemo
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards

  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.microdemo.svc.cluster.local:3100
        access: proxy
        isDefault: false
        version: 1
        editable: true

      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated:9090
        access: proxy
        isDefault: true
        version: 1
        editable: true
