apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: api
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 8000
      protocol: TCP
  type: {{ .Values.service.api.type }}
