apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microdemo-envs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: microdemo-dev
            host: dev.api.your-real-domain.com
            imageTag: v1.0.0
          - env: prod
            namespace: microdemo
            host: api.your-real-domain.com
            imageTag: v1.0.0
  template:
    metadata:
      name: 'microdemo-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/microservices_k8s_demo.git
        targetRevision: main
        path: helm/microdemo
        helm:
          parameters:
            - name: namespace
              value: '{{namespace}}'
            - name: image.registry
              value: ghcr.io/your-org/microdemo
            - name: image.api.tag
              value: '{{imageTag}}'
            - name: image.worker.tag
              value: '{{imageTag}}'
            - name: ingress.enabled
              value: "true"
            - name: ingress.className
              value: nginx
            - name: ingress.host
              value: '{{host}}'
            - name: ingress.tls.enabled
              value: "true"
            - name: ingress.tls.secretName
              value: microdemo-tls
            - name: ingress.annotations.cert-manager\.io/cluster-issuer
              value: letsencrypt
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
