apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microdemo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/microservices_k8s_demo.git
    targetRevision: main
    path: helm/microdemo
    helm:
      parameters:
        - name: namespace
          value: microdemo
        - name: image.registry
          value: ghcr.io/your-org/microdemo
        - name: image.api.tag
          value: v1.0.0
        - name: image.worker.tag
          value: v1.0.0
        - name: ingress.enabled
          value: "true"
        - name: ingress.className
          value: nginx
        - name: ingress.host
          value: api.your-real-domain.com
        - name: ingress.tls.enabled
          value: "true"
        - name: ingress.tls.secretName
          value: microdemo-tls
        - name: ingress.annotations.cert-manager\.io/cluster-issuer
          value: letsencrypt
  destination:
    server: https://kubernetes.default.svc
    namespace: microdemo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
