apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: microdemo
spec:
  replicas: 1
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels: { app: worker }
    spec:
      containers:
        - name: worker
          image: local/worker:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: api-config
