apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker
  namespace: microdemo
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: worker
  namespaceSelector:
    matchNames: [ microdemo ]
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
