apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: microdemo
  labels:
    release: prometheus   # adjust to your Prometheus Operator's selector
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames:
      - microdemo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
