apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: microdemo
spec:
  replicas: 1
  selector:
    matchLabels: { app: loki }
  template:
    metadata:
      labels: { app: loki }
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.8
          args: [ "-config.file=/etc/loki/loki.yaml" ]
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
      volumes:
        - name: config
          configMap:
            name: loki-config
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: microdemo
spec:
  selector: { app: loki }
  ports:
    - port: 3100
      targetPort: 3100
