apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
images:
  - name: local/api
    newName: local/api
    newTag: dev
  - name: local/worker
    newName: local/worker
    newTag: dev
patches:
  - target:
      version: v1
      kind: Deployment
      name: api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
