name: Release & Push to GHCR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push API
        uses: docker/build-push-action@v5
        with:
          context: ./services/api
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/microdemo/api:${{ github.event.inputs.version || github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/${{ secrets.GHCR_USERNAME }}/microdemo/api:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ secrets.GHCR_USERNAME }}/microdemo/api:buildcache,mode=max

      - name: Build & Push Worker
        uses: docker/build-push-action@v5
        with:
          context: ./services/worker
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/microdemo/worker:${{ github.event.inputs.version || github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/${{ secrets.GHCR_USERNAME }}/microdemo/worker:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ secrets.GHCR_USERNAME }}/microdemo/worker:buildcache,mode=max
